import json
from pathlib import Path

from retrieve_knowledge import retrieve_relevant_knowledge


REASONING_CONTEXT_PATH = (
    "data/structured/reasoning_context.json"
)

OUTPUT_PATH = (
    "data/structured/rag_reasoning_context.json"
)


def load_reasoning_context():
    """Load the output produced by reasoning_engine.py."""

    with open(REASONING_CONTEXT_PATH, "r") as f:
        return json.load(f)


def retrieve_evidence_for_interaction(
    interaction,
    top_k=3
):
    """
    Retrieve scientific evidence from ChromaDB
    using the evidence query generated by the
    reasoning engine.
    """

    query = interaction.get(
        "evidence_query",
        ""
    )

    if not query:
        return []

    try:
        documents, ids = retrieve_relevant_knowledge(
            query,
            top_k=top_k
        )
    except Exception as e:
        return []

    evidence = []

    for doc_id, document in zip(
        ids,
        documents
    ):
        evidence.append({
            "id": doc_id,
            "text": document
        })

    return evidence


def attach_evidence(context):
    """
    Retrieve evidence for every detected
    multi-variable interaction.
    """

    interactions = context.get(
        "multi_variable_interactions",
        []
    )

    enriched_interactions = []

    for i, interaction in enumerate(
        interactions,
        start=1
    ):


        evidence = retrieve_evidence_for_interaction(
            interaction,
            top_k=3
        )

        interaction_copy = dict(
            interaction
        )

        interaction_copy[
            "scientific_evidence"
        ] = evidence

        enriched_interactions.append(
            interaction_copy
        )


    context["multi_variable_interactions"] = (
        enriched_interactions
    )

    return context


def save_context(context):
    Path(OUTPUT_PATH).parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(OUTPUT_PATH, "w") as f:
        json.dump(
            context,
            f,
            indent=2
        )



def print_evidence(context):

    print("\n" + "=" * 70)
    print("SCIENTIFIC EVIDENCE RETRIEVAL")
    print("=" * 70)

    for interaction in context[
        "multi_variable_interactions"
    ]:

        print(
            f"\nINTERACTION: "
            f"{interaction['interaction']}"
        )

        print(
            "Query: "
            + interaction["evidence_query"]
        )

        evidence = interaction.get(
            "scientific_evidence",
            []
        )

        if not evidence:
            print(
                "  No evidence retrieved."
            )
            continue

        for i, item in enumerate(
            evidence,
            start=1
        ):

            print(
                f"\n  Evidence {i}"
            )

            print(
                f"  ID: {item['id']}"
            )

            print(
                f"  {item['text'][:500]}"
            )

            if len(item["text"]) > 500:
                print("  ...")

    print("\n" + "=" * 70)


if __name__ == "__main__":

    print(
        "Loading reasoning context..."
    )

    context = load_reasoning_context()

    print(
        "Running scientific evidence retrieval..."
    )

    context = attach_evidence(
        context
    )

    print_evidence(
        context
    )

    save_context(
        context
    )